x-env-loader: &env-loader
  env_file:
    - .env.config

x-logging: &logging
  logging:
    driver: fluentd
    options:
      fluentd-address: localhost:24224
      fluentd-async: "true"
      tag: "docker.{{.Name}}"
      fluentd-sub-second-precision: "true"

services:
  ros2:
    image: us-docker.pkg.dev/practical-cider-485717-k0/prod-images/ros2:1.1.8
    <<: [*env-loader, *logging]
    platform: linux/amd64
    environment:
      - INFLUXDB_URL=http://host.docker.internal:8086
      - INFLUXDB_ORG=anvil
      - INFLUXDB_BUCKET=workcell
      - INFLUXDB_TOKEN=anvil-workcell
      - WEBAPP_URL=http://127.0.0.1:3000
    volumes:
      - ./config:/config
      - ./data:/data
      - /etc/machine-id:/etc/machine-id:ro
      - ./.android:/root/.android
      - /run/cameras:/run/cameras:ro
    privileged: true
    network_mode: host
    depends_on:
      fluent-bit:
        condition: service_healthy
      influxdb:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    stop_signal: SIGINT

  webapps:
    image: us-docker.pkg.dev/practical-cider-485717-k0/prod-images/webapps:1.1.8
    <<: [*env-loader, *logging]
    ports:
      - 3000:3000
    environment:
      - VERSION=1.1.8
      - NODE_ENV=production
      - DATA_DIR=/data
      - MIGRATIONS_FOLDER=/app/migrations
      - ROS_WS_ENDPOINT=ws://host.docker.internal:9090
    volumes:
      - ./data:/data
      - /etc/machine-id:/etc/machine-id:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - workcell-network
    depends_on:
      fluent-bit:
        condition: service_healthy
      ros2:
        condition: service_started
    restart: unless-stopped

  influxdb:
    image: us-docker.pkg.dev/practical-cider-485717-k0/prod-images/influxdb:1.1.8
    <<: *logging
    user: "0:0"
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb3:/var/lib/influxdb3
    depends_on:
      fluent-bit:
        condition: service_healthy
    environment:
      - INFLUXDB_PORT=8086
      - INFLUXDB_CLOUD_URL
      - INFLUXDB_CLOUD_BUCKET
      - INFLUXDB_CLOUD_TOKEN
    networks:
      - workcell-network
    restart: unless-stopped

  telegraf:
    image: us-docker.pkg.dev/practical-cider-485717-k0/prod-images/telegraf:1.1.8
    <<: [*env-loader, *logging]
    user: telegraf:444
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /run/udev:/run/udev:ro
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - ROS_WS_ENDPOINT=ws://host.docker.internal:9090
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=anvil
      - INFLUXDB_BUCKET=workcell
      - INFLUXDB_TOKEN=anvil-workcell
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - workcell-network
    depends_on:
      fluent-bit:
        condition: service_healthy
      influxdb:
        condition: service_started
    restart: unless-stopped

  fluent-bit:
    image: us-docker.pkg.dev/practical-cider-485717-k0/prod-images/fluent-bit:1.1.8
    <<: *env-loader
    ports:
      - 24224:24224
      - 2020:2020
    volumes:
      - /var/log:/var/log:ro
      - ./data/fluent-bit:/data
      - /etc/machine-id:/etc/machine-id:ro
      - .git:/repo-git:ro
    environment:
      - DEVICE_NAME
      - VERSION=1.1.8
      - GRAFANA_LOKI_HOST
      - GRAFANA_LOKI_USER
      - GRAFANA_LOKI_API_KEY
    command: /fluent-bit/bin/fluent-bit -q -c /fluent-bit/etc/fluent-bit-cloud.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - workcell-network
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2020/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s
    restart: unless-stopped

networks:
  workcell-network:
    driver: bridge
